name: "Release"

on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: npm i -g pnpm@11.5.2
      # conventionalcommits v10はrelease notesが空になるバグがあるため9.3.1に固定
      # https://github.com/semantic-release/release-notes-generator/issues/992
      - run: |
          pnpm dlx \
             --package semantic-release@24.2.9 \
             --package conventional-changelog-conventionalcommits@9.3.1 \
             --package @semantic-release/git@10.0.1 \
             --package @semantic-release/exec@7.1.0 \
              semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
