name: "Release"

on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: npm i -g pnpm@11.0.8
      - run: |
          pnpm dlx \
             --package semantic-release@24 \
             --package conventional-changelog-conventionalcommits \
             --package @semantic-release/git \
             --package @semantic-release/exec \
              semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
